[project]
name = "xt"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.119.0",
    "fastmcp>=2.12.5",
    "pandas>=2.3.3",
    "pandas-stubs==2.3.2.250926",
    "pytz>=2025.2",
    "requests>=2.32.5",
    "uvicorn>=0.38.0",
]
