[project]
name = "xt"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.120.2",
    "fastmcp>=2.13.0.2",
    "pandas>=2.3.3",
    "pandas-stubs~=2.3.3",
    "pytz>=2025.2",
    "requests>=2.32.5",
    "uvicorn>=0.38.0",
]
